import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Main from "../components/Main";

export default function Home() {
  // const [isPlaying, setIsPlaying] = useState(true);

  return (
    <div>
      <Head>
        <title>Satellite Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        {/* <h1>Satellite Labs</h1> */}
        <video src={require("../assets/videobg.mp4")} autoPlay loop muted />
      </Body>
    </div>
  );
}

const Body = styled.div`
  height: 100vh;
  width: 100vw;
  display: grid;
  align-items: center;
  text-align: center;
  justify-content: space-evenly;

  > h1 {
    font-size: 30px;
    color: white;
    padding-bottom: 20px;
    font-family: "Inter Regular";

    :hover {
      cursor: pointer;
    }
  }

  > p {
    font-size: 16px;
    color: white;
    padding-bottom: 20px;
  }
`;
