import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Satellite Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <h1>Satellite Labs</h1>
        <h1>Explore</h1>
      </Body>
    </div>
  );
}

const Body = styled.div`
  padding: 20px;
  height: 100vh;

  > h1 {
    font-size: 20px;
    color: white;
    padding-bottom: 20px;
    font-family: "Inter Regular";
  }

  > p {
    font-size: 16px;
    color: white;
    padding-bottom: 20px;
  }
`;
